
project_id = "mukqpwinqhdfffdkthcg"

[functions.categorize-request]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.accept-invitation]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-approve-user]
verify_jwt = true
