project_id = "mukqpwinqhdfffdkthcg"

[functions.flush-maintenance-requests]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.event-bus]
verify_jwt = false
